services:
# TODO: пофиксить dockerfile, почему-то выходит ошибка 401
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "${APP_PORT}:${APP_PORT}"
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
#    depends_on:
#      - postgres

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: